apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: follow-service
  name: follow-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: follow-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: follow-service
    spec:
      containers:
        - env:
            - name: MONGO_URI
              value: mongodb://root:example@mongodb:27017/follow_service_db?authSource=admin
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          image: ahmedhamed22/follow-ms:latest
          name: follow-ms-container
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
