apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: newsfeed-ms
  name: newsfeed-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: newsfeed-ms
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: newsfeed-ms
    spec:
      containers:
        - env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          image: ahmedhamed22/newsfeed-ms:latest
          name: newsfeed-ms-container
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
