apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: video-ms
  name: video-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: video-ms
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: video-ms
    spec:
      containers:
        - env:
            - name: MINIO_ENDPOINT
              value: http://minio:9000
            - name: MINIO_ROOT_PASSWORD
              value: minio123
            - name: MINIO_ROOT_USER
              value: minio
            - name: NEWSFEED_SERVICE_URL
              value: http://newsfeed-ms:8080/newsFeed
            - name: MONGO_URI
              value: mongodb://root:example@mongodb:27017/video_metadata_db?authSource=admin
          image: ahmedhamed22/video-ms:latest
          name: video-ms-container
          ports:
            - containerPort: 8080
              protocol: TCP
#          volumeMounts:
#            - mountPath: /opt/videos
#              name: video-ms-cm0
      restartPolicy: Always
#      volumes:
#        - configMap:
#            name: video-ms-cm0
#          name: video-ms-cm0
